# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sv.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(697, 515)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 321, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Image1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.Image1.setObjectName("Image1")
        self.horizontalLayout.addWidget(self.Image1)
        self.Image1_options = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.Image1_options.setObjectName("Image1_options")
        self.Image1_options.addItem("")
        self.Image1_options.addItem("")
        self.Image1_options.addItem("")
        self.Image1_options.addItem("")
        self.horizontalLayout.addWidget(self.Image1_options)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 321, 171))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Image1_original = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.Image1_original.setObjectName("Image1_original")
        self.horizontalLayout_2.addWidget(self.Image1_original)
        self.Image1_new = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.Image1_new.setObjectName("Image1_new")
        self.horizontalLayout_2.addWidget(self.Image1_new)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 230, 321, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Image2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.Image2.setObjectName("Image2")
        self.horizontalLayout_3.addWidget(self.Image2)
        self.Image2_options = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.Image2_options.setObjectName("Image2_options")
        self.Image2_options.addItem("")
        self.Image2_options.addItem("")
        self.Image2_options.addItem("")
        self.Image2_options.addItem("")
        self.horizontalLayout_3.addWidget(self.Image2_options)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 260, 321, 171))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Image2_original = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.Image2_original.setObjectName("Image2_original")
        self.horizontalLayout_4.addWidget(self.Image2_original)
        self.Image2_new = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.Image2_new.setObjectName("Image2_new")
        self.horizontalLayout_4.addWidget(self.Image2_new)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(350, 10, 321, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.mixerOutput = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.mixerOutput.setObjectName("mixerOutput")
        self.horizontalLayout_5.addWidget(self.mixerOutput)
        self.MixerOut_Options = QtWidgets.QComboBox(self.horizontalLayoutWidget_5)
        self.MixerOut_Options.setObjectName("MixerOut_Options")
        self.MixerOut_Options.addItem("")
        self.MixerOut_Options.addItem("")
        self.horizontalLayout_5.addWidget(self.MixerOut_Options)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(350, 50, 321, 41))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.component1 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.component1.setObjectName("component1")
        self.horizontalLayout_6.addWidget(self.component1)
        self.component1_ImageSelection = QtWidgets.QComboBox(self.horizontalLayoutWidget_6)
        self.component1_ImageSelection.setObjectName("component1_ImageSelection")
        self.component1_ImageSelection.addItem("")
        self.component1_ImageSelection.addItem("")
        self.horizontalLayout_6.addWidget(self.component1_ImageSelection)
        spacerItem = QtWidgets.QSpacerItem(58, 36, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.component1_Slider = QtWidgets.QSlider(self.horizontalLayoutWidget_6)
        self.component1_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.component1_Slider.setObjectName("component1_Slider")
        self.horizontalLayout_6.addWidget(self.component1_Slider)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(430, 100, 241, 31))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.component1_MixingParameter = QtWidgets.QComboBox(self.horizontalLayoutWidget_7)
        self.component1_MixingParameter.setObjectName("component1_MixingParameter")
        self.component1_MixingParameter.addItem("")
        self.component1_MixingParameter.addItem("")
        self.component1_MixingParameter.addItem("")
        self.component1_MixingParameter.addItem("")
        self.component1_MixingParameter.addItem("")
        self.component1_MixingParameter.addItem("")
        self.horizontalLayout_7.addWidget(self.component1_MixingParameter)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(350, 140, 321, 41))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.component2 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.component2.setObjectName("component2")
        self.horizontalLayout_8.addWidget(self.component2)
        self.component2_ImageSelection = QtWidgets.QComboBox(self.horizontalLayoutWidget_8)
        self.component2_ImageSelection.setObjectName("component2_ImageSelection")
        self.component2_ImageSelection.addItem("")
        self.component2_ImageSelection.addItem("")
        self.horizontalLayout_8.addWidget(self.component2_ImageSelection)
        spacerItem1 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.component2_Slider = QtWidgets.QSlider(self.horizontalLayoutWidget_8)
        self.component2_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.component2_Slider.setObjectName("component2_Slider")
        self.horizontalLayout_8.addWidget(self.component2_Slider)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(429, 190, 241, 31))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.component2_MixingParameter = QtWidgets.QComboBox(self.horizontalLayoutWidget_9)
        self.component2_MixingParameter.setObjectName("component2_MixingParameter")
        self.component2_MixingParameter.addItem("")
        self.component2_MixingParameter.addItem("")
        self.component2_MixingParameter.addItem("")
        self.component2_MixingParameter.addItem("")
        self.component2_MixingParameter.addItem("")
        self.component2_MixingParameter.addItem("")
        self.horizontalLayout_9.addWidget(self.component2_MixingParameter)
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(350, 240, 321, 31))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.Output1 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.Output1.setObjectName("Output1")
        self.horizontalLayout_10.addWidget(self.Output1)
        self.Output2 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.Output2.setObjectName("Output2")
        self.horizontalLayout_10.addWidget(self.Output2)
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(350, 270, 321, 161))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.Output1_Image = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.Output1_Image.setObjectName("Output1_Image")
        self.horizontalLayout_11.addWidget(self.Output1_Image)
        self.Output2_Image = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.Output2_Image.setObjectName("Output2_Image")
        self.horizontalLayout_11.addWidget(self.Output2_Image)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 697, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Image1.setText(_translate("MainWindow", "Image 1  "))
        self.Image1_options.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.Image1_options.setItemText(1, _translate("MainWindow", "Phase"))
        self.Image1_options.setItemText(2, _translate("MainWindow", "Real"))
        self.Image1_options.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.Image1_original.setText(_translate("MainWindow", "TextLabel"))
        self.Image1_new.setText(_translate("MainWindow", "TextLabel"))
        self.Image2.setText(_translate("MainWindow", "Image 2"))
        self.Image2_options.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.Image2_options.setItemText(1, _translate("MainWindow", "Phase"))
        self.Image2_options.setItemText(2, _translate("MainWindow", "Real"))
        self.Image2_options.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.Image2_original.setText(_translate("MainWindow", "TextLabel"))
        self.Image2_new.setText(_translate("MainWindow", "TextLabel"))
        self.mixerOutput.setText(_translate("MainWindow", "Mixer Output to:"))
        self.MixerOut_Options.setItemText(0, _translate("MainWindow", "Output1"))
        self.MixerOut_Options.setItemText(1, _translate("MainWindow", "Output2"))
        self.component1.setText(_translate("MainWindow", "Component 1"))
        self.component1_ImageSelection.setItemText(0, _translate("MainWindow", "Image1"))
        self.component1_ImageSelection.setItemText(1, _translate("MainWindow", "Image2"))
        self.component1_MixingParameter.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.component1_MixingParameter.setItemText(1, _translate("MainWindow", "Phase"))
        self.component1_MixingParameter.setItemText(2, _translate("MainWindow", "Real"))
        self.component1_MixingParameter.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.component1_MixingParameter.setItemText(4, _translate("MainWindow", "uniMagitude"))
        self.component1_MixingParameter.setItemText(5, _translate("MainWindow", "uniPhase"))
        self.component2.setText(_translate("MainWindow", "Component 2"))
        self.component2_ImageSelection.setItemText(0, _translate("MainWindow", "Image1"))
        self.component2_ImageSelection.setItemText(1, _translate("MainWindow", "Image2"))
        self.component2_MixingParameter.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.component2_MixingParameter.setItemText(1, _translate("MainWindow", "Phase"))
        self.component2_MixingParameter.setItemText(2, _translate("MainWindow", "Real"))
        self.component2_MixingParameter.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.component2_MixingParameter.setItemText(4, _translate("MainWindow", "uniMagnitude"))
        self.component2_MixingParameter.setItemText(5, _translate("MainWindow", "uniPhase"))
        self.Output1.setText(_translate("MainWindow", "Output 1"))
        self.Output2.setText(_translate("MainWindow", "Output 2"))
        self.Output1_Image.setText(_translate("MainWindow", "TextLabel"))
        self.Output2_Image.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

